<?php

namespace Tests\Feature;

use App\Models\Pelanggan;
use App\Models\Pembayaran;
use App\Models\Penggunaan;
use App\Models\Tagihan;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class PembayaranTest extends TestCase
{
    protected $user;
    protected $pelanggan;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = User::where('username', 'admin')->where('password', 'admin')->first();
        $this->pelanggan = Pelanggan::where('username', 'pelanggan')->where('password', 'pelanggan')->first();
    }
    /**
     * A basic feature test example.
     */
    public function test_confirm_pembayaran(): void
    {
        $penggunaan = Penggunaan::factory()->create(['id_pelanggan' => $this->pelanggan->id_pelanggan, 'meter_awal'=>500, 'meter_akhir'=>1300]);
        $tagihan = Tagihan::where('id_pelanggan', $this->pelanggan->id_pelanggan)->where('bulan', $penggunaan->bulan)->where('tahun', $penggunaan->tahun)->where('jumlah_meter', '800')->where('status', null)->first();
        $response = $this->actingAs($this->user, 'customer')->patch('/tagihan/'.$tagihan->id_tagihan);
        $bayar = Pembayaran::where('id_tagihan', $tagihan->id_tagihan)->where('id_pelanggan', $this->pelanggan->id_pelanggan)->where('bulan_bayar', $tagihan->bulan)->first();
        $response = $this->actingAs($this->user, 'admin')->put('admin/pembayaran/'.$tagihan->id_tagihan);
        $response->assertStatus(302)->assertRedirect('/admin/pembayaran');
        Penggunaan::where('id_pelanggan', $penggunaan->id_pelanggan)->where('bulan', $penggunaan->bulan)->where('tahun', $penggunaan->tahun)->where('meter_awal', $penggunaan->meter_awal)->where('meter_akhir', $penggunaan->meter_akhir)->delete();
    }
}
