<?php

namespace Tests\Feature;

use App\Models\Pelanggan;
use App\Models\Penggunaan;
use App\Models\Tagihan;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class TagihanTest extends TestCase
{
    protected $user;
    protected $pelanggan;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = User::where('username', 'admin')->where('password', 'admin')->first();
        $this->pelanggan = Pelanggan::where('username', 'pelanggan')->where('password', 'pelanggan')->first();
    }

    /**
     * A basic feature test example.
     */
    public function test_pelanggan_can_see_tagihan(): void
    {
        $response = $this->actingAs($this->pelanggan, 'customer')->get('/tagihan');
        $response->assertStatus(200)->assertSee('Tagihan Penggunaan Listrik');
    }
    public function test_pelanggan_can_process_tagihan(): void
    {
        $penggunaan = Penggunaan::factory()->create(['id_pelanggan' => $this->pelanggan->id_pelanggan, 'bulan' => 12, 'tahun' =>2048, 'meter_awal'=>2500, 'meter_akhir'=>3080]);;
        $tagihan = Tagihan::where('id_pelanggan', $this->pelanggan->id_pelanggan)->where('bulan', $penggunaan->bulan)->where('tahun', $penggunaan->tahun)->where('jumlah_meter', '580')->where('status', null)->first();
        $response = $this->actingAs($this->user, 'customer')->patch('/tagihan/'.$tagihan->id_tagihan);
        $response->assertStatus(302)->assertRedirect('/tagihan');
    }
    public function test_admin_can_delete_tagihan_pelanggan(): void
    {
        $penggunaan = Penggunaan::factory()->create(['id_pelanggan' => $this->pelanggan->id_pelanggan, 'meter_awal'=>500, 'meter_akhir'=>1300]);
        $tagihan = Tagihan::where('id_pelanggan', $this->pelanggan->id_pelanggan)->where('bulan', $penggunaan->bulan)->where('tahun', $penggunaan->tahun)->where('jumlah_meter', '800')->where('status', null)->first();
        $response = $this->actingAs($this->user, 'admin')->delete('admin/penggunaan/detail_tagihan/'.$tagihan->id_tagihan);
        $response->assertStatus(302)->assertRedirect('/admin/penggunaan');
        Penggunaan::where('id_pelanggan', $penggunaan->id_pelanggan)->where('bulan', $penggunaan->bulan)->where('tahun', $penggunaan->tahun)->where('meter_awal', $penggunaan->meter_awal)->where('meter_akhir', $penggunaan->meter_akhir)->delete();
    }
}
